export const ADD_ITEM = 'ADD_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const TOGGLE_ITEM = 'TOGGLE_ITEM'

export const UPDATE_PERSISTANT_STORE = 'UPDATE_PERSISTANT_STORE'
export const UPDATE_PERSISTANT_STORE_SUCCESS = 'UPDATE_PERSISTANT_STORE_SUCCESS'
export const UPDATE_PERSISTANT_STORE_FAILURE = 'UPDATE_PERSISTANT_STORE_FAILURE'


export const FETCH_PERSISTANT_STORE_SUCCESS = 'FETCH_PERSISTANT_STORE_SUCCESS'
export const FETCH_PERSISTANT_STORE_FAILURE = 'FETCH_PERSISTANT_STORE_FAILURE'


export const SUBMIT_FORM = 'SUBMIT_FORM'
